from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.maximize_window()
driver.get('https://www.facebook.com')
time.sleep(5)
print(driver.title)
print(driver.current_url)
driver.refresh()
driver.get('https://www.google.co.in')
time.sleep(5)
print(driver.title)
print(driver.current_url)
driver.back()
time.sleep(5)
print(driver.title)
print(driver.current_url)
driver.forward()
time.sleep(5)
print(driver.title)
print(driver.current_url)
driver.close()
